openapi: 3.0.0
info:
  title: Chad Movies API
  description: Chad Movie API
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: https://api-chad-movies.nikoloz.redberryinternship.ge/api
    description: production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /login:
    post:
      summary: User login
      responses:
        "200":
          description: User logged in successfully
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

  /register:
    post:
      summary: User registration
      responses:
        "200":
          description: User created successfully
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string

  /authorize/google/redirect:
    get:
      summary: Google redirect url
      responses:
        "200":
          description: Google callback.

  /authorize/google/callback:
    get:
      responses:
        "200":
          description: User created successfully.
      parameters:
        - in: path
          name: code
          required: true
          schema:
            type: string

  /email-verification:
    get:
      summary: Email verification.
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          description: The id of user email verification
        - in: query
          name: hash
          schema:
            type: string
          description: The hash of email verification
      responses:
        "200":
          description: OK

  /forgot-password:
    post:
      summary: User forgot password
      responses:
        "201":
          description: Reset Email is send successfully, please check your inbox.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string

  /reset-password:
    post:
      summary: User reset password
      responses:
        "200":
          description: Your password has been updated <3.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string

  /logout:
    post:
      summary: User logout
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successfully logged out.

  /checkToken:
    post:
      summary: User can check bearer token validation
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Okay

  /notifications:
    post:
      summary: Return read and unread notification arrays
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Return read and unread notification arrays

  /markAsRead:
    post:
      summary: Mark notification read
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Notification read

  /markAllAsRead:
    post:
      summary: Mark all notification read
      security:
        - bearerAuth: []
      responses:
        "200":
          description: All notifications read

  /profile:
    put:
      summary: Update user profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Profile updated successfully

  /movies:
    post:
      summary: User can add movie
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Movie added successfully.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title_en:
                  type: string
                  example: Sherekilebi
                title_ka:
                  type: string
                  example: შერეკილები
                director_en:
                  type: string
                  example: Ermalo
                director_ka:
                  type: string
                  example: ერმალო
                genre:
                  type: string
                  example: Horror
                description_en:
                  type: string
                  example: Mdzafri
                description_ka:
                  type: string
                  example: მძაფრი
                year:
                  type: integer
                  example: 1999
                budget:
                  type: integer
                  example: 2394232
                thumbnail:
                  type: string
                  example: base
    get:
      summary: Return movies array
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Okay.

  /movies/{movie}:
    get:
      summary: Show single movie
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: movie
          schema:
            type: integer
          required: true
          description: Numeric ID of the movie
      responses:
        "201":
          description: Okay.
    put:
      summary: User can update movie
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Movie updated successfully.
      parameters:
        - in: path
          name: movie
          schema:
            type: integer
          required: true
          description: Numeric ID of the movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title_en:
                  type: string
                  example: Sherekilebi
                title_ka:
                  type: string
                  example: შერეკილები
                director_en:
                  type: string
                  example: Ermalo
                director_ka:
                  type: string
                  example: ერმალო
                genre:
                  type: string
                  example: Horror
                description_en:
                  type: string
                  example: Mdzafri
                description_ka:
                  type: string
                  example: მძაფრი
                year:
                  type: integer
                  example: 1999
                budget:
                  type: integer
                  example: 2394232
                thumbnail:
                  type: string
                  example: base
    delete:
      summary: Delete single movie
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: movie
          schema:
            type: integer
          required: true
          description: Numeric ID of the movie
      responses:
        "204":
          description: Okay.

  /quotes:
    post:
      summary: User can add quote
      security:
        - bearerAuth: []
      responses:
        "201":
          description: quote added successfully.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quote_en:
                  type: string
                  example: quote
                quote_ka:
                  type: string
                  example: ციტატა
                movie_id:
                  type: integer
                  example: 1
                thumbnail:
                  type: string
                  example: base
    get:
      summary: Return quotes array
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Okay.
  /quotes/{quote}:
    get:
      summary: Show single quote
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: quote
          schema:
            type: integer
          required: true
          description: Numeric ID of the quote
      responses:
        "201":
          description: Okay.
    put:
      summary: User can update quote
      security:
        - bearerAuth: []
      responses:
        "201":
          description: quote updated successfully.
      parameters:
        - in: path
          name: quote
          schema:
            type: integer
          required: true
          description: Numeric ID of the quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quote_en:
                  type: string
                  example: newquote
                quote_ka:
                  type: string
                  example: ახალიციტატა
                thumbnail:
                  type: string
                  example: base
    delete:
      summary: Delete single quote
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: quote
          schema:
            type: integer
          required: true
          description: Numeric ID of the quote
      responses:
        "204":
          description: Okay.

  /users:
    get:
      summary: Return users array
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Okay.

  /genres:
    get:
      summary: Return genres array
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Okay.

  /movie-slug/{id}:
    get:
      summary: Show single movie by slug
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the movie
      responses:
        "201":
          description: Okay.

  /search:
    get:
      summary: Return searched quotes
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Okay.

  /like/{quote}:
    post:
      summary: Like quote
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: quote
          schema:
            type: integer
          required: true
          description: Numeric ID of the quote
      responses:
        "200":
          description: Quote liked successfully.
    delete:
      summary: Unlike quote
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: quote
          schema:
            type: integer
          required: true
          description: Numeric ID of the quote
      responses:
        "200":
          description: Quote unliked successfully.
